0.1.2

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1043,7 +1043,6 @@ Optional Packages:
   --with-tags[=TAGS]
                           include additional configurations [automatic]
   --with-openssl          Encryption support [default=yes]
-  --with-pthread          Encryption support [default=yes]
 
 Some influential environment variables:
   CC          C compiler command
@@ -1806,7 +1805,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=libipmsg
- VERSION=0.1.1
+ VERSION=0.1.2
 
 
 cat >>confdefs.h <<_ACEOF
@@ -3663,7 +3662,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3666 "configure"' > conftest.$ac_ext
+  echo '#line 3665 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5262,7 +5261,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5265:" \
+echo "$as_me:5264:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6325,11 +6324,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6328: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6327: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6332: \$? = $ac_status" >&5
+   echo "$as_me:6331: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6593,11 +6592,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6596: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6595: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6600: \$? = $ac_status" >&5
+   echo "$as_me:6599: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6697,11 +6696,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6700: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6699: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6704: \$? = $ac_status" >&5
+   echo "$as_me:6703: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8166,7 +8165,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 8169 "configure"' > conftest.$ac_ext
+    echo '#line 8168 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -9063,7 +9062,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9066 "configure"
+#line 9065 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9163,7 +9162,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9166 "configure"
+#line 9165 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11503,11 +11502,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11506: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11505: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11510: \$? = $ac_status" >&5
+   echo "$as_me:11509: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -11607,11 +11606,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11610: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11609: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11614: \$? = $ac_status" >&5
+   echo "$as_me:11613: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12143,7 +12142,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 12146 "configure"' > conftest.$ac_ext
+    echo '#line 12145 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -13198,11 +13197,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13201: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13200: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13205: \$? = $ac_status" >&5
+   echo "$as_me:13204: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13302,11 +13301,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13305: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13304: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13309: \$? = $ac_status" >&5
+   echo "$as_me:13308: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14751,7 +14750,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 14754 "configure"' > conftest.$ac_ext
+    echo '#line 14753 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -15526,11 +15525,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15529: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15528: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15533: \$? = $ac_status" >&5
+   echo "$as_me:15532: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15794,11 +15793,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15797: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15796: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15801: \$? = $ac_status" >&5
+   echo "$as_me:15800: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15898,11 +15897,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15901: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15900: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15905: \$? = $ac_status" >&5
+   echo "$as_me:15904: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17367,7 +17366,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 17370 "configure"' > conftest.$ac_ext
+    echo '#line 17369 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -22456,22 +22455,13 @@ else
 	echo libipmsg was not support encryption.
 fi
 
-
-# Check whether --with-pthread or --without-pthread was given.
-if test "${with_pthread+set}" = set; then
-  withval="$with_pthread"
-
-else
-  with_pthread=yes
-fi;
-if test "x$with_pthread" = xyes; then
-	echo "checking for pthread..."
-	have_pthread_create=yes
-	have_pthread_detach=yes
-	have_pthread_mutex_init=yes
-	have_pthread_mutex_lock=yes
-	have_pthread_mutex_unlock=yes
-	echo "$as_me:$LINENO: checking for pthread_create in -lpthread" >&5
+echo "checking for pthread..."
+have_pthread_create=yes
+have_pthread_detach=yes
+have_pthread_mutex_init=yes
+have_pthread_mutex_lock=yes
+have_pthread_mutex_unlock=yes
+echo "$as_me:$LINENO: checking for pthread_create in -lpthread" >&5
 echo $ECHO_N "checking for pthread_create in -lpthread... $ECHO_C" >&6
 if test "${ac_cv_lib_pthread_pthread_create+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -22541,7 +22531,7 @@ else
   have_pthread_create=no
 fi
 
-	echo "$as_me:$LINENO: checking for pthread_detach in -lpthread" >&5
+echo "$as_me:$LINENO: checking for pthread_detach in -lpthread" >&5
 echo $ECHO_N "checking for pthread_detach in -lpthread... $ECHO_C" >&6
 if test "${ac_cv_lib_pthread_pthread_detach+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -22611,7 +22601,7 @@ else
   have_pthread_detach=no
 fi
 
-	echo "$as_me:$LINENO: checking for pthread_mutex_init in -lpthread" >&5
+echo "$as_me:$LINENO: checking for pthread_mutex_init in -lpthread" >&5
 echo $ECHO_N "checking for pthread_mutex_init in -lpthread... $ECHO_C" >&6
 if test "${ac_cv_lib_pthread_pthread_mutex_init+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -22681,7 +22671,7 @@ else
   have_pthread_mutex_init=no
 fi
 
-	echo "$as_me:$LINENO: checking for pthread_mutex_lock in -lpthread" >&5
+echo "$as_me:$LINENO: checking for pthread_mutex_lock in -lpthread" >&5
 echo $ECHO_N "checking for pthread_mutex_lock in -lpthread... $ECHO_C" >&6
 if test "${ac_cv_lib_pthread_pthread_mutex_lock+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -22751,7 +22741,7 @@ else
   have_pthread_mutex_lock=no
 fi
 
-	echo "$as_me:$LINENO: checking for pthread_mutex_unlock in -lpthread" >&5
+echo "$as_me:$LINENO: checking for pthread_mutex_unlock in -lpthread" >&5
 echo $ECHO_N "checking for pthread_mutex_unlock in -lpthread... $ECHO_C" >&6
 if test "${ac_cv_lib_pthread_pthread_mutex_unlock+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -22821,24 +22811,21 @@ else
   have_pthread_mutex_unlock=no
 fi
 
-	if test "x$have_pthread_create" = xyes &&
-	   test "x$have_pthread_detach" = xyes &&
-	   test "x$have_pthread_mutex_init" = xyes &&
-	   test "x$have_pthread_mutex_lock" = xyes &&
-	   test "x$have_pthread_mutex_unlock" = xyes ;then
+if test "x$have_pthread_create" = xyes &&
+   test "x$have_pthread_detach" = xyes &&
+   test "x$have_pthread_mutex_init" = xyes &&
+   test "x$have_pthread_mutex_lock" = xyes &&
+   test "x$have_pthread_mutex_unlock" = xyes ;then
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_PTHREAD 1
 _ACEOF
 
-		echo POSIX thread support enabled.
-	else
-		{ { echo "$as_me:$LINENO: error: --with-pthread was given, but test for libpthread failed" >&5
-echo "$as_me: error: --with-pthread was given, but test for libpthread failed" >&2;}
-   { (exit 1); exit 1; }; }
-	fi
+	echo POSIX thread support enabled.
 else
-	echo libipmsg was not support POSIX thread.
+	{ { echo "$as_me:$LINENO: error: libipmsg required pthread library, but test for libpthread failed" >&5
+echo "$as_me: error: libipmsg required pthread library, but test for libpthread failed" >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 # Check whether --enable-debug or --disable-debug was given.
